#!/bin/sh /etc/rc.common
#
# Copyright (c) 2016 Arduino Srl
# This file is part of Arduino Ciao.
#
# Starts stnfcd
#

START=52
STOP=52

NAME=stnfcd
DAEMON=/usr/bin/$NAME

# Exit gracefully if the package has been removed
[ -x $DAEMON ] || exit 0
[ -e /dev/ttyUSB0 ] || exit 0

start () {
    echo -n "Starting $NAME: "
    service_start $DAEMON /dev/ttyUSB0
    echo "OK"
}

stop () {
    echo -n "Stopping $NAME: "
    service_stop $DAEMON
    echo "OK"
}

reload () {
    service_reload $DAEMON /dev/ttyUSB0
}
