#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=49

start() {
	[ -e /etc/smartme/smartme_gpg.asc ] && echo "nothing to do !" && exit 0
	logger -t gpg "Generating GPG key..."
	/usr/bin/gpg --batch --gen-key /etc/smartme/gpg_gen_key_batch
	logger -t gpg "GPG key generated. Exporting key as ascii text file..."
	rm -f /etc/smartme/smartme_gpg.asc
	/usr/bin/gpg --no-default-keyring --secret-keyring /etc/smartme/smartme_gpg.sec --keyring /etc/smartme/smartme_gpg.pub --export --armor --output /etc/smartme/smartme_gpg.asc
	logger -t gpg "GPG key exported"
}
